[3502] Add Code Climate test coverage to pipeline
This script download and install the code climate test report binary
but only if all our other tasks/tests pass. The reporter submits the
test coverage which was generated from RSPEC using Simplecov.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -69,11 +69,18 @@ steps:
 
 - bash: |
     set -x
-    docker run --rm $(IMAGE_NAME) rails spec SPEC_OPTS='--format RspecJunitFormatter' >rspec-results.xml
+    docker run --name test-run-image -d $(IMAGE_NAME)
+    docker exec test-run-image rails spec SPEC_OPTS='--format RspecJunitFormatter'
     test_result=$?
-    cat  --number rspec-results.xml
-    sed -i '1,2d' rspec-results.xml
-    if [ "$test_result" == "0" ] ; then true ; else false ; fi
+      if [ "$test_result" != "0" ]
+      then
+          echo "##vso[task.logissue type=error] Test task failed."
+          exit 1
+      fi
+
+    docker cp test-run-image:/app/coverage .
+    docker stop test-run-image
+    docker rm test-run-image
   displayName: 'Run Ruby tests'
 
 - task: Docker@1
@@ -83,6 +90,22 @@ steps:
     imageName: $(IMAGE_NAME)
     containerCommand: yarn test
     runInBackground: false
+
+- script: |
+    set -x
+    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
+    chmod +x ./cc-test-reporter
+
+    ./cc-test-reporter before-build
+    # As the tests were run in the docker container the paths to the coverage are prefixed with "/app/"
+    # So we need to replace it with the docker hosts current directory
+    sed "s|\"/app/|\"`pwd`/|g" coverage/.resultset.json -i
+    ./cc-test-reporter after-build
+  displayName: 'Publish Code Climate Test Coverage'
+  env:
+    CC_TEST_REPORTER_ID: $(ccReporterID)
+    AGENT_JOBSTATUS: $(Agent.JobStatus)
+    GIT_BRANCH: $(Build.SourceBranchName)
 
 - task: Docker@1
   displayName: Tag image with current build number $(Build.BuildNumber)
